spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/hongdosanDB?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username : hongdosan
    password : hongdosan

jwt:
  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M